###### STRING database #######
STITCH_cutoff: 0.4

STITCH_mapping_url: "http://stitch.embl.de/download/chemical.aliases.v5.0.tsv.gz"

STITCH_url: "http://stitch.embl.de/download/protein_chemical.links.detailed.v5.0/9606.protein_chemical.links.detailed.v5.0.tsv.gz"

STITCH_actions_url: "http://stitch.embl.de/download/actions.v5.0/9606.actions.v5.0.tsv.gz"

header:
  - "START_ID"
  - "END_ID"
  - "TYPE"
  - "interaction_type"
  - "source"
  - "evidence"
  - "scores"
  - "score"

header_actions:
  - "START_ID"
  - "END_ID"
  - "TYPE"
  - "action"
  - "directionality"
  - "score"
  - "source"
