###### STRING database #######
STRING_cutoff: 0.4

STRING_mapping_url: "https://stringdb-static.org/download/protein.aliases.v11.0/9606.protein.aliases.v11.0.txt.gz"

STRING_url: "https://stringdb-static.org/download/protein.links.detailed.v11.0/9606.protein.links.detailed.v11.0.txt.gz"

STRING_actions_url: "https://stringdb-static.org/download/protein.actions.v11.0/9606.protein.actions.v11.0.txt.gz"

header:
  - "START_ID"
  - "END_ID"
  - "TYPE"
  - "interaction_type"
  - "source"
  - "evidence"
  - "scores"
  - "score"

header_actions:
  - "START_ID"
  - "END_ID"
  - "TYPE"
  - "action"
  - "directionality"
  - "score"
  - "source"
